plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.hunurgencias'
    compileSdk 35

    defaultConfig {
        applicationId 'es.aviso.hun.urgencias'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '1.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
